# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c3d028f614a8150e1a09552f3b6786473883303df422c2ff239004e6460a9d50cc2027d37f0539fbb3f3a9b5d0ca1191dce2a765cedc8387042d79c9bbd0ce9

test:
  secret_key_base: c908230da96751db69421b084616afc30710c6fd4f8026934140fa3317a2a3ecbb1951ce79196ae9dd99a4e06e6475eefc74812b83fafaa45ed3e5e5dfd0a56c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
